--- ./file-server/Dockerfile	2022-12-13 09:04:16.121171800 +0200
+++ ../polis-digifinland-tools/file-server/Dockerfile	2022-12-13 09:07:29.646961700 +0200
@@ -5,7 +5,9 @@
 
 RUN apk add git g++ make python openssh --no-cache
 
-
+RUN git config --global url."https://github.com/".insteadOf git@github.com: \
+    && git config --global url."https://".insteadOf git:// \
+    && git config --global url."https://github.com/".insteadOf ssh://git@github.com
 
 # polis-client-admin
 FROM client-base AS client-admin
