version: "3.4"

services:
  server:
    env_file: ./server/docker-${DOCKER_ENV}-digifinland.env
    image: europe-north1-docker.pkg.dev/polis-kokeilu/polis-kokeilu-test/polis-server:${DOCKER_ENV}
    depends_on:
      - "file-server"
    networks:
      - "polis-net"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure
    ports:
      - target: 5000
        published: 5000-5005
        protocol: tcp
        mode: ingress
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first      
      restart_policy:
        condition: always
        delay: 5s
        # max_attempts: 3
        window: 120s  

  math:
    container_name: polis-math
    env_file: ./math/docker-${DOCKER_ENV}-digifinland.env
    image: europe-north1-docker.pkg.dev/polis-kokeilu/polis-kokeilu-test/polis-math:${DOCKER_ENV}
    build:
      context: ./math
    networks:
      - "polis-net"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      restart_policy:
        condition: always
        delay: 5s
        # max_attempts: 3
        window: 120s        

  file-server:
    container_name: polis-file-server
    image: europe-north1-docker.pkg.dev/polis-kokeilu/polis-kokeilu-test/polis-file-server:${DOCKER_ENV}
    build:
      context: ./
      dockerfile: file-server/Dockerfile
      args:
        GIT_HASH: "${GIT_HASH}"
    networks:
      - "polis-net"
    deploy:
      restart_policy:
        condition: always
        delay: 5s
        # max_attempts: 3
        window: 120s              

networks:
  polis-net:

volumes:
  backups:
  postgres:
