apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: polis
build:
  local:
    useBuildkit: true
    push: false
  artifacts:
  - image: docker.io/compdem/polis-file-server
    context: ../polis
    docker:
      dockerfile: ../polis/file-server/Dockerfile
  - image: docker.io/compdem/polis-math
    context: ../polis/math
    docker:
      dockerfile: ../polis/math/Dockerfile
#  - image: docker.io/compdem/polis-postgres
#    context: ../polis/server
#    docker:
#      dockerfile: ../polis/server/Dockerfile-db
  - image: docker.io/compdem/polis-server
    context: ../polis/server
    docker:
      dockerfile: ../polis/server/Dockerfile
deploy:
  kubectl:
    manifests:
    - manifests/localbuild/polis-file-server.yaml
    - manifests/localbuild/polis-math.yaml
#    - manifests/postgres.yaml
    - manifests/localbuild/polis-server.yaml
