apiVersion: v1
kind: Secret
metadata:
  name: polis-server-secret
type: Opaque
data:
  # base64 encoded value: 
  DATABASE_URL: postgres://user:password@ipaddress:port/databasename
  # Note(geoah): This seems to be needed until the following TODO is resolved:
  # https://github.com/compdemocracy/polis/blob/9a294140bbfc50d5bbb50ce4e474f4ad72541881/server/src/session.ts#L8-L10
  # base64 encoded value:  
  ENCRYPTION_PASSWORD_00001: CHANGEME
  # base64 encoded value:  
  MAILGUN_API_KEY: CHANGEME
  # base64 encoded value:  
  GOOGLE_CREDENTIALS_BASE64: CHANGEME
