blank_issues_enabled: false
contact_links:
  - name: DigiFinland Polis project
    url: https://digifinland.fi/toimintamme/polis-kansalaiskeskustelualusta/
    about: Official project page in Finnish
